<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 >Week 23 Class 3 03/01</h1>
</div>

## Objectives for this week:
* Continuing Machine Learning

## Todays Agenda
* Clustering Example
* Review numpy and pandas
* Some helpful videos


<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Review Day</h1>
</div>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Numpy

### creating numpy arrays

In [2]:
one_dimensional_array = np.array([1,2,3,4,5])
one_dimensional_array

array([1, 2, 3, 4, 5])

In [3]:
one_dimensional_array.shape

(5,)

In [4]:
# array = [[1,2],[3,4,],[5,6]]
#array = ((1,2),(3,4,),(5,6))
array_dict = {1:2, 3:4, 5:6}

two_dimensional_array = np.array(list(array_dict.items()))
two_dimensional_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
array = [[[1,2],[3,4]],[[3,4,],[5,6]]]

three_dimensional_array = np.array(array)
three_dimensional_array

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 6]]])

In [6]:
three_dimensional_array.shape

(2, 2, 2)

In [7]:
two_dimensional_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
two_dimensional_array.shape

(3, 2)

# Placeholders

`np.zeros` takes a shape and returns a np array of that shape filled with zeros

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

`np.ones` takes a shape and returns a `np.array` of that shape filled with ones

In [10]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

`np.arange` takes python slice format as argument (`start, stop, skip`) and returns a `np.array` of that range and skip.

note: stop is still exclusive as always

In [11]:
np.arange(10,25,5)

array([10, 15, 20])

`np.linspace` almost takes python slice format as argument as well and returns the range from `start` to `stop` (exclusive) but instead of `skip`, the third argument is the number of evenly spaced elements you need

In [12]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

`np.eye` takes an `int n` as argument and returns a $ n * n $ identity matrix

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Inspecting your numpy array

In [14]:
a = np.linspace(0,10,11)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
a.shape

(11,)

In [16]:
len(a)

11

In [17]:
a.ndim

1

In [18]:
a.size

11

In [19]:
a.dtype

dtype('float64')

In [20]:
a.astype(int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Broadcasting

Instead of looping through a `np.array`, we can simply perform arithmetic operations and each element will be affected

In [21]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
a ** 2

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [23]:
a + 5

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [24]:
a / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
a * 100

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

### Special math functions

These aren't broadcasted. Same indexed elements are computed together.

In [26]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
b = np.arange(5,16,1)
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
np.add(a,b)

array([ 5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.])

In [29]:
np.subtract(a,b)

array([-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.])

In [30]:
np.divide(a,b)

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444,
       0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714,
       0.66666667])

In [31]:
np.multiply(a,b)

array([  0.,   6.,  14.,  24.,  36.,  50.,  66.,  84., 104., 126., 150.])

In [32]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [33]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [34]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [35]:
np.cos(b)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791])

In [36]:
np.log(b)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])

In [37]:
a = np.array([[1,2],[3,4]])
b = np.eye(2)
a, b

(array([[1, 2],
        [3, 4]]),
 array([[1., 0.],
        [0., 1.]]))

In [38]:
a.dot(b)

array([[1., 2.],
       [3., 4.]])

# Comparison

In [39]:
a = np.array([[1,2],[3,4]])
b = np.eye(2)
a,b

(array([[1, 2],
        [3, 4]]),
 array([[1., 0.],
        [0., 1.]]))

In [40]:
a == b

array([[ True, False],
       [False, False]])

In [41]:
a < 2

array([[ True, False],
       [False, False]])

In [42]:
np.array_equal(a,b)

False

# Aggregate Functions

In [43]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [44]:
a.sum()

10

In [45]:
a.min()

1

In [46]:
a.max(axis=0)

array([3, 4])

In [47]:
a.max(axis=1)

array([2, 4])

In [48]:
a.cumsum(axis=0)

array([[1, 2],
       [4, 6]], dtype=int32)

In [49]:
a.cumsum(axis=1)

array([[1, 3],
       [3, 7]], dtype=int32)

In [50]:
a.mean()

2.5

In [51]:
np.std(a)

1.118033988749895

In [52]:
a.sort()
a

array([[1, 2],
       [3, 4]])

In [53]:
a = np.array([[1,0,3],[3,1,2]])
a.sort(axis=0)
a

array([[1, 0, 2],
       [3, 1, 3]])

In [54]:
a.sort(axis=1)
a

array([[0, 1, 2],
       [1, 3, 3]])

### Slicing/Indexing

In [55]:
a = np.array([[1,0,3],[3,1,2]])
a

array([[1, 0, 3],
       [3, 1, 2]])

In [56]:
a[1]

array([3, 1, 2])

In [57]:
a[1][2]

2

In [58]:
a[1,2]

2

In [59]:
a[a<3]

array([1, 0, 1, 2])

In [60]:
a[1,1:]

array([1, 2])

In [61]:
a[:,0::2]

array([[1, 3],
       [3, 2]])

In [62]:
a[::-1]

array([[3, 1, 2],
       [1, 0, 3]])

### Reshaping

In [63]:
a.T

array([[1, 3],
       [0, 1],
       [3, 2]])

In [64]:
a.ravel()

array([1, 0, 3, 3, 1, 2])

In [65]:
a.reshape(3,2)

array([[1, 0],
       [3, 3],
       [1, 2]])

In [66]:
b = np.array([4,5,6])
c = np.append(a,b)
c

array([1, 0, 3, 3, 1, 2, 4, 5, 6])

In [67]:
np.zeros(10).resize(2,10)

# Pandas

### Series

A one-dimensional labeled array capable of holding any data type

In [68]:
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
s

a    3
b   -5
c    7
d    4
dtype: int64

A two-dimensional labeled data structure with columns of potentially different types

In [69]:
data = {'Country': ['Belgium',  'India',  'Brazil'],
        'Capital': ['Brussels',  'New Delhi',  'Brasilia'],
        'Population': [11190846, 1303171035, 207847528]
}
df = pd.DataFrame(data,columns=['Country',  'Capital',  'Population'])
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

Please note that the first column 1,2,3 is the index and Country,Capital,Population are the Columns.

Asking For Help

In [70]:
help(pd.Series.loc)

Help on property:

    Access a group of rows and columns by label(s) or a boolean array.
    
    ``.loc[]`` is primarily label based, but may also be used with a
    boolean array.
    
    Allowed inputs are:
    
    - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
      interpreted as a *label* of the index, and **never** as an
      integer position along the index).
    - A list or array of labels, e.g. ``['a', 'b', 'c']``.
    - A slice object with labels, e.g. ``'a':'f'``.
    
      .. warning:: Note that contrary to usual python slices, **both** the
          start and the stop are included
    
    - A boolean array of the same length as the axis being sliced,
      e.g. ``[True, False, True]``.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that returns valid output for indexing (one of the above)
    
    See more at :ref:`Selection by Label <indexing.label>`
    
    Raises
    ------
    KeyError
        If any it

### I/O
Read and Write to CSV

In [71]:
pd.read_csv('file.csv', header=None, nrows=5)
df.to_csv('file.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'file.csv'

In [ ]:
xlsx = pd.ExcelFile('file.xls')
df = pd.read_excel(xlsx,  'Sheet1')

Read and Write to Excel

In [ ]:
pd.read_excel('file.xlsx')
df.to_excel('file.xlsx',  sheet_name='Sheet1')

Read and Write to SQL Query or Database Table

(read_sql()is a convenience wrapper around read_sql_table() and read_sql_query())

In [ ]:
import sqlite3

conn = sqlite3.connect('../week-022/students.db')

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///../week-022/students.db')
pd.read_sql('SELECT * FROM student;', engine)
pd.read_sql_query('SELECT * FROM student;', engine)

In [ ]:
df.to_sql('new_table', engine)

### Selection

Getting

Get one element

In [ ]:
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
s

In [ ]:
s['b']

Get subset of a DataFrame

In [ ]:
xlsx = pd.ExcelFile('file.xls')
df = pd.read_excel(xlsx,  'Sheet1')
df[0:]

In [ ]:
df.iloc[0:,1:]

### Selecting, Boolean Indexing and Setting
By Position

Select single value by row and and column

In [ ]:
data = {'Country': ['Belgium',  'India',  'Brazil'],
        'Capital': ['Brussels',  'New Delhi',  'Brasilia'],
        'Population': [11190846, 1303171035, 207847528]
}
df = pd.DataFrame(data,columns=['Country',  'Capital',  'Population'])
df.iloc[[0], [0]]

Getting a specific index

In [ ]:
df.iat[0, 0]

By Label

Select single value by row and column labels

In [ ]:
df.loc[[0],  ['Country']]

In [ ]:
df.at[0,  'Country']

In [ ]:
df.loc[1, :]

In [ ]:
df.loc[:, ['Capital']]

Select rows and columns

In [ ]:
df.loc[1, 'Capital']

### Boolean Indexing

Series s where value is not >1

In [ ]:
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
s[~(s > 1)]

s where value is `s <-1` or `s>2`

In [ ]:
s[(s < -1) | (s > 2)]

Use filter to adjust DataFrame

In [ ]:
df[df['Population']>1200000000]

### Setting

Set index a of Series s to 6

In [ ]:
s['a'] = 6
s

### Dropping

Drop values from rows (axis=0)

In [ ]:
s.drop(['a',  'c'])

Drop values from columns(axis=1)

In [ ]:
df.drop('Country', axis=1) 

### Sort and Rank

Sort by labels along an axis

In [ ]:
df.sort_index()

Sort by the values along an axis

In [ ]:
df.sort_values(by='Country') 

### Assign ranks to entries

In [ ]:
df.rank()

### Retrieving Series/DataFrame Information

Basic Information

(rows, columns)

In [ ]:
df.shape

Describe index

In [ ]:
df.index

Describe DataFrame columns

In [ ]:
df.columns

Info on DataFrame

In [ ]:
df.info()

In [ ]:
Number of non-NA values

In [ ]:
df.count()

In [ ]:
df.notna().sum()

### Summary

Sum of values

In [ ]:
df.sum()

Cumulative sum of values

In [ ]:
df.cumsum()

Minimum/maximum values

In [ ]:
df.min()

In [ ]:
df.max()

Minimum/Maximum index value

In [ ]:
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
s

In [ ]:
s.idxmin()

In [ ]:
s.idxmax() 

Summary statistics

In [ ]:
data = {'Country': ['Belgium',  'India',  'Brazil'],
        'Capital': ['Brussels',  'New Delhi',  'Brasilia'],
        'Population': [11190846, 1303171035, 207847528]
}
df = pd.DataFrame(data,columns=['Country',  'Capital',  'Population'])
df.describe()

Mean of values

In [ ]:
df.mean()

Median of values

In [ ]:
df.median()

In [ ]:
df = pd.DataFrame([[]])
df['Population'].mode()

Applying Functions

In [ ]:
f = lambda x: x*2

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

Apply function

`apply` works row/column-wise

In [ ]:
frame.apply(f)

`applymap` works element-wise

In [ ]:
frame.applymap(f)

`map` works element-wise on a `Series`

In [ ]:
frame['b'].map(f)

### Internal Data Alignment

NA values are introduced in the indices that don't overlap:

In [ ]:
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
s3 = pd.Series([7, -2, 3],  index=['a',  'c',  'd'])
s + s3

### Arithmetic Operations with Fill Methods

You can also do the internal data alignment yourself with the help of the fill methods:

In [ ]:
s.add(s3, fill_value=0)

In [ ]:
s.sub(s3, fill_value=2)

In [ ]:
s.div(s3, fill_value=4)

In [ ]:
s.mul(s3, fill_value=3)

# Resources:

https://www.kaggle.com/lavanyashukla01/pandas-numpy-python-cheatsheet



<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Clustering Example</h1>
</div>

https://www.youtube.com/watch?v=4b5d3muPQmA

This is the "Iris" dataset. Originally published at [UCI Machine Learning Repository: Iris Data Set](https://archive.ics.uci.edu/ml/datasets/Iris), this small dataset from 1936 is often used for testing out machine learning algorithms and visualizations (for example, [Scatter Plot](http://bl.ocks.org/curran/9e04ccfebeb84bcdc76c)). Each row of the table represents an iris flower, including its species and dimensions of its botanical parts, sepal and petal, in centimeters.

In [ ]:
# Code source: Gaël Varoquaux
# Modified for documentation by Jaques Grobler
# License: BSD 3 clause

import numpy as np
import matplotlib.pyplot as plt
# Though the following import is not directly being used, it is required
# for 3D projection to work
from mpl_toolkits.mplot3d import Axes3D

# import KMeans from cluster module
from sklearn.cluster import KMeans

# import datasets included in sklearn
from sklearn import datasets

# this seeds our PRNG so our random numbers
# aren't random
np.random.seed(5)

# loads the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# we're going to run 3 different versions of our KMeans
# one with 8 clusters
# one with 3 clusters
# one with 1 to 3 clusters initialized randomly and 
# meant to try a few different numbers and pick the best
estimators = [('k_means_iris_8', KMeans(n_clusters=8)),
              ('k_means_iris_3', KMeans(n_clusters=3)),
              ('k_means_iris_bad_init', KMeans(n_clusters=3, n_init=1,
                                               init='random'))]

# Now we set up a chart for our results
# we'll make 3 for each run of our KMeans algorithm
fignum = 1
titles = ['8 clusters', '3 clusters', '3 clusters, bad initialization']
for name, est in estimators:
    fig = plt.figure(fignum, figsize=(4, 3))
    ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)
    est.fit(X)
    labels = est.labels_

    ax.scatter(X[:, 3], X[:, 0], X[:, 2],
               c=labels.astype(float), edgecolor='k')

    ax.w_xaxis.set_ticklabels([])
    ax.w_yaxis.set_ticklabels([])
    ax.w_zaxis.set_ticklabels([])
    ax.set_xlabel('Petal width')
    ax.set_ylabel('Sepal length')
    ax.set_zlabel('Petal length')
    ax.set_title(titles[fignum - 1])
    ax.dist = 12
    fignum = fignum + 1

# Plot the real clustering
fig = plt.figure(fignum, figsize=(4, 3))
ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)

for name, label in [('Setosa', 0),
                    ('Versicolour', 1),
                    ('Virginica', 2)]:
    ax.text3D(X[y == label, 3].mean(),
              X[y == label, 0].mean(),
              X[y == label, 2].mean() + 2, name,
              horizontalalignment='center',
              bbox=dict(alpha=.2, edgecolor='w', facecolor='w'))
# Reorder the labels to have colors matching the cluster results
y = np.choose(y, [1, 2, 0]).astype(float)
ax.scatter(X[:, 3], X[:, 0], X[:, 2], c=y, edgecolor='k')

ax.w_xaxis.set_ticklabels([])
ax.w_yaxis.set_ticklabels([])
ax.w_zaxis.set_ticklabels([])
ax.set_xlabel('Petal width')
ax.set_ylabel('Sepal length')
ax.set_zlabel('Petal length')
ax.set_title('Ground Truth')
ax.dist = 12

fig.show()

<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Videos</h1>
</div>

Logistic Regression:  
https://www.youtube.com/watch?v=yIYKR4sgzI8

KMeans Clustering
https://www.youtube.com/watch?v=4b5d3muPQmA

Cross-Validation:  
https://www.youtube.com/watch?v=fSytzGwwBVw

The Confusion Matrix:  
https://www.youtube.com/watch?v=Kdsp6soqA7o