<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Week 24 Lab</h1>
</div>


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Part 1 - Python Problems
<hr>

### Exercise 1

Create a function that takes a list of integers and calculates the mean. Use the following formula for calculating averages and not any `mean`/`average` method.

$$ \mu = {\frac {1}{n}}\sum _{i=1}^{n}a_{i}={\frac {a_{1}+a_{2}+\cdots +a_{n}}{n}}$$

In [2]:
example_list = [1,2,3,4,5,6,7,8,9]
example_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
avg = sum(example_list) / len(example_list) 
avg

5.0

In [4]:
df = pd.DataFrame(example_list)
df.mean()

0    5.0
dtype: float64

In [5]:
df.median()

0    5.0
dtype: float64

### Exercise 2

Create a class that operates like a stack.  

In [6]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        pass

    def pop(self):
        return self.items.pop()

    def peek(self):
        return self.items[len(self.items)-1]

    def size(self):
        return len(self.items)

In [7]:
s = Stack()
s.push('Hello')
s.push('World')
# print(s.pop())

### Exercise 3

Write a generator function which returns a few values and then use it to retrieve a value using `next` (the global function). 

In [8]:
n = np.random.randint(1,60,size=20)
n

array([22, 51, 51, 52,  3,  9, 26, 33, 56,  3, 54,  1, 45, 50, 55, 14, 33,
        7, 29, 44])

In [9]:
def genFun(n):
    for num in n:
        yield num

x = genFun(n)

In [10]:
next(x)

22

### Exercise 4

Create a namedtuple `'Point'` that contains the points `x` and `y`.

In [11]:
from collections import namedtuple 

In [12]:
Point = namedtuple('Point', ['x', 'y'])
p1 = Point(10,20)
p2 = Point(30,40)
print(p1,p2)
print(p1.x, p2.y)

Point(x=10, y=20) Point(x=30, y=40)
10 40


### Exercise 5

Create a moving average class that:
* has a method `add` that is used to add new values
* has a method `avg` that calculates the average of the 5 most recently added values
* has an attribute `values` that contain all values added
* has an attribute `window` that contains the 5 most recently added values

In [13]:
class MovingAvg:
#     has an attribute values that contain all values added
#     has an attribute window that contains the 5 most recently added values
    def __init__(self, values, window):
        self.values = values
        self.window = window

    def __add__(self):
        pass

    def __avg__(self):
        pass


## Part 2 - Numpy Problems
<hr>

### Exercise 1

Using numpy, create an array that contains the values of $y$ for each of the $x$ values ranging from 0 to 100.

$$ y = 12x+4  $$

In [14]:
# 𝑥  values ranging from 0 to 100.
x = np.arange(0,101)
y = 12*x + 4
y

array([   4,   16,   28,   40,   52,   64,   76,   88,  100,  112,  124,
        136,  148,  160,  172,  184,  196,  208,  220,  232,  244,  256,
        268,  280,  292,  304,  316,  328,  340,  352,  364,  376,  388,
        400,  412,  424,  436,  448,  460,  472,  484,  496,  508,  520,
        532,  544,  556,  568,  580,  592,  604,  616,  628,  640,  652,
        664,  676,  688,  700,  712,  724,  736,  748,  760,  772,  784,
        796,  808,  820,  832,  844,  856,  868,  880,  892,  904,  916,
        928,  940,  952,  964,  976,  988, 1000, 1012, 1024, 1036, 1048,
       1060, 1072, 1084, 1096, 1108, 1120, 1132, 1144, 1156, 1168, 1180,
       1192, 1204])

### Exercise 2

Create a 2-dimensional numpy array that contains the numbers from 1 to 20 with even numbers in the first column and odd numbers in the second.

In [15]:
# Create a 2-dimensional numpy array that contains the numbers from 1 to 20
_2D = np.arange(1,21)
_2D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
# even numbers in the first column and odd numbers in the second.
# ndarray.T The transposed array.
np.array([_2D[_2D%2==0], _2D[_2D%2==1]]).T

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9],
       [12, 11],
       [14, 13],
       [16, 15],
       [18, 17],
       [20, 19]])

### Exercise 3

Create a numpy array with random numbers between 0 and 1.

In [17]:
# random numbers between 0 and 1.
random_int = np.random.uniform(0,1,10) #start, stop, size
random_int

array([0.55079862, 0.06455747, 0.35428119, 0.86565124, 0.4082878 ,
       0.18411095, 0.31512758, 0.97973413, 0.4513893 , 0.14226907])

# Exercise 4

Create an array that contains 100 numbers. All of them between 0 and 5. Then add that to an array that contains the numbers from 0 to 99.

In [18]:
# Create an array that contains 100 numbers. 
# All of them between 0 and 5.
contains_arr = np.random.uniform(0,5,100)
# Then add that to an array that contains the numbers from 0 to 99.
add_arr = np.arange(0,100)
c = contains_arr  + add_arr
c

array([  0.48969829,   1.91092557,   4.09274816,   5.32746769,
         7.74632571,   9.17959359,   7.11169586,  10.44200161,
         8.5438417 ,  11.76144028,  10.49707421,  11.912264  ,
        12.60973016,  17.46803704,  16.93994632,  18.6247704 ,
        17.45143161,  18.20679025,  18.67796358,  22.44906698,
        23.65652734,  21.39761061,  26.65364929,  24.89276177,
        25.637905  ,  26.82253494,  29.28675852,  29.05793742,
        28.23197119,  32.19777971,  31.08143286,  33.53389368,
        36.32327379,  37.24141399,  38.68377217,  39.31649556,
        37.92859373,  40.86924106,  41.8800622 ,  42.71035872,
        43.46384843,  44.5567561 ,  46.37090792,  44.93323619,
        48.58541849,  48.41998073,  47.63787331,  51.60959195,
        52.12918792,  50.89880549,  52.76085288,  55.06720601,
        53.85751786,  54.14664435,  54.30104314,  59.53191613,
        57.44924742,  60.72596201,  59.40919693,  61.34242447,
        61.76509106,  61.22523166,  63.1385585 ,  64.87

### Exercise 5

Create a 10 by 10 matrix containing zeros. Then create a 10 by 10 matrix containing ones. Combine the two matrices so that the new dimensions are 20 by 10.

In [19]:
# Create a 10 by 10 matrix containing zeros. 
z = np.zeros((10,10))
# Then create a 10 by 10 matrix containing ones.
o = np.ones((10,10))
# ombine the two matrices so that the new dimensions are 20 by 10.
# Join a sequence of arrays along an existing axis
zo = np.concatenate((z, o))
zo

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 6

Given the following numpy array, find the cumulative sum along the rows. Then find the cumulative sum along the columns. Then output the 2nd (1st index) column but only the first 10 rows. You should get a very recognizable pattern.

In [20]:
# Given the following numpy array, find the cumulative sum along the rows. T
a = np.array([[0,1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10,0], [2,3,4,5,6,7,8,9,10,0,1], [3,4,5,6,7,8,9,10,0,1,2],[4,5,6,7,8,9,10,0,1,2,3],[5,6,7,8,9,10,0,1,2,3,4],[6,7,8,9,10,0,1,2,3,4,5],[7,8,9,10,0,1,2,3,4,5,6],[8,9,10,0,1,2,3,4,5,6,7],[9,10,0,1,2,3,4,5,6,7,8],[10,0,1,2,3,4,5,6,7,8,9]])
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1],
       [ 3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2],
       [ 4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6],
       [ 8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [21]:
# Then find the cumulative sum along the columns. 
np.cumsum(a, axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 19, 11],
       [ 6, 10, 14, 18, 22, 26, 30, 34, 27, 20, 13],
       [10, 15, 20, 25, 30, 35, 40, 34, 28, 22, 16],
       [15, 21, 27, 33, 39, 45, 40, 35, 30, 25, 20],
       [21, 28, 35, 42, 49, 45, 41, 37, 33, 29, 25],
       [28, 36, 44, 52, 49, 46, 43, 40, 37, 34, 31],
       [36, 45, 54, 52, 50, 48, 46, 44, 42, 40, 38],
       [45, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55]], dtype=int32)

In [22]:
#  Then output the 2nd (1st index) column but only the first 10 rows. 
np.cumsum(a, axis=1)

array([[ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55],
       [ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 55],
       [ 2,  5,  9, 14, 20, 27, 35, 44, 54, 54, 55],
       [ 3,  7, 12, 18, 25, 33, 42, 52, 52, 53, 55],
       [ 4,  9, 15, 22, 30, 39, 49, 49, 50, 52, 55],
       [ 5, 11, 18, 26, 35, 45, 45, 46, 48, 51, 55],
       [ 6, 13, 21, 30, 40, 40, 41, 43, 46, 50, 55],
       [ 7, 15, 24, 34, 34, 35, 37, 40, 44, 49, 55],
       [ 8, 17, 27, 27, 28, 30, 33, 37, 42, 48, 55],
       [ 9, 19, 19, 20, 22, 25, 29, 34, 40, 47, 55],
       [10, 10, 11, 13, 16, 20, 25, 31, 38, 46, 55]], dtype=int32)

### Exercise 7

Using the following string. Turn it into a numpy array where all the letters are their own element.

In [23]:
s = "helloworld"

In [24]:
# Turn it into a numpy array where all the letters are their own element.
_s = np.array(list(s))
_s

array(['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd'], dtype='<U1')

### Exercise 8

How would we flatten the following array?

In [25]:
a = np.eye(10)

In [26]:
x.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Part 3 - Pandas Problems
<hr>

**1.** Create a dataframe using the following:

In [27]:
lst = [['Red',4],['Blue',6],['Green',1],\
       ['Yellow',5],['White',3],['Black',2],]
lst

[['Red', 4],
 ['Blue', 6],
 ['Green', 1],
 ['Yellow', 5],
 ['White', 3],
 ['Black', 2]]

In [28]:
df_lst = pd.DataFrame(lst)
df_lst

0  1
0     Red  4
1    Blue  6
2   Green  1
3  Yellow  5
4   White  3
5   Black  2

**2.** Create a dataframe using the following:

In [29]:
dct = {'red':4, 'blue':6, 'green':1,\
       'yellow':5, 'white':3, 'black':2 }


In [30]:
df_dct = pd.DataFrame.from_dict(dct, orient='index')
df_dct

0
red     4
blue    6
green   1
yellow  5
white   3
black   2

**The following exercises will use the dataset imported below:**


In [31]:
df = pd.DataFrame([[np.nan,'Toyota','Camry',336978, 24765,np.nan],[2019,'Toyota','Corolla',304850, np.nan,4560556],[2019,'Toyota','Supra',np.nan, 35545,102511.78],[2019,np.nan,'Avalon',np.nan ,36480,1012940.16]])
df.columns = ['year', 'make', 'model', 'number sold', 'price', 'revenue (in thousands)']
df

year    make    model  number sold    price  revenue (in thousands)
0     NaN  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 4

Fix the `year` column in the dataframe by replacing missing values with the average value of that column.

In [32]:
df['year'] = df['year'].fillna(df['year'].mean()).astype(int)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0                     NaN
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 5

Fix the `'make'` column by replacing the missing value with the value that occurred most frequently (mode).

In [33]:
df["make"].fillna( method ='ffill', limit = 1, inplace = True)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0                     NaN
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 6

Fix the `'revenue (in thousands)'` column by calculating the approximate revenue. Remember that the value of `'revenue'` is in the 1000s.

$$ \textrm{revenue} = \textrm{number sold} * \textrm{price} $$

In [34]:
df['revenue (in thousands)'] = df['revenue (in thousands)'].fillna(0)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0                    0.00
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

In [35]:
# revenue=number sold∗price
df["revenue (in thousands)"] = df["revenue (in thousands)"].fillna((df["number sold"]*df["price"])/1000)
df


year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0                    0.00
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 7

Fix the `'price'` column by calculating the approximate price.

$$ \textrm{price} = \frac{\textrm{revenue}}{\textrm{number sold}} $$

In [36]:
df["price"] = df["price"].fillna((df["revenue (in thousands)"]/df["number sold"]))
df


year    make    model  number sold     price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.00                    0.00
1  2019  Toyota  Corolla     304850.0     14.96              4560556.00
2  2019  Toyota    Supra          NaN  35545.00               102511.78
3  2019  Toyota   Avalon          NaN  36480.00              1012940.16

### Exercise 8

Fix the `'number sold'` column by calculating the approximate number of vehicles sold.

$$ \textrm{number sold} = \frac{\textrm{revenue}}{\textrm{price}} $$

In [37]:
df["number sold"] = df["number sold"].fillna((df["revenue (in thousands)"]/df["price"]))
df


year    make    model  number sold     price  revenue (in thousands)
0  2019  Toyota    Camry   336978.000  24765.00                    0.00
1  2019  Toyota  Corolla   304850.000     14.96              4560556.00
2  2019  Toyota    Supra        2.884  35545.00               102511.78
3  2019  Toyota   Avalon       27.767  36480.00              1012940.16