<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 >Week 17 Project</h1>
</div>


Complete the following parts:

### Part 1 
In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

<p class="monospace center">
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08<br />
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00<br />
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65<br />
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91<br />
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80<br />
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50<br />
32 98 81 28 64 23 67 10 <span style="color:red;"><b>26</b></span> 38 40 67 59 54 70 66 18 38 64 70<br />
67 26 20 68 02 62 12 20 95 <span  style="color:red;"><b>63</b></span> 94 39 63 08 40 91 66 49 94 21<br />
24 55 58 05 66 73 99 26 97 17 <span  style="color:red;"><b>78</b></span> 78 96 83 14 88 34 89 63 72<br />
21 36 23 09 75 00 76 44 20 45 35 <span  style="color:red;"><b>14</b></span> 00 61 33 97 34 31 33 95<br />
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92<br />
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57<br />
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58<br />
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40<br />
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66<br />
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69<br />
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36<br />
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16<br />
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54<br />
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48<br /></p>
<p>The product of these numbers is 26 × 63 × 78 × 14 = 1788696.</p>
<p>What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?</p>

Use numpy or pandas as needed.

In [1]:
import numpy as np
import pandas as pd

grid = \
"""
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
"""

In [2]:
# Create grid
grid_lst = grid.split(" ")

grid_int = [x.split('\n') for x in grid_lst]
grid_arr = []

for i in grid_int:
    for r in i:
        if r != "":
            grid_arr.append(int(r))

In [3]:
# Step 1: convert string to 2d np.array
grid_np_arr = np.array(grid_arr).reshape((20, 20))
grid_np_arr

array([[ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12,
        50, 77, 91,  8],
       [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,
         4, 56, 62,  0],
       [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3,
        49, 13, 36, 65],
       [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71,
        37,  2, 36, 91],
       [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28,
        66, 33, 13, 80],
       [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20,
        35, 17, 12, 50],
       [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66,
        18, 38, 64, 70],
       [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91,
        66, 49, 94, 21],
       [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88,
        34, 89, 63, 72],
       [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97,
        34, 31, 33, 95],
       [78, 17, 53, 28, 22, 75

In [ ]:
# 1. For Each row, do
#    a) get 4 adjacent numbers
#    b) get the product of those numbers
#    c) store the product in a sepearte array (results_array)
#    d) move to the next 4 digits

In [27]:
RESULT_ARRAY = []

In [28]:
# Adjacent rows (LEFT/RIGHT)
for i in range(grid_np_arr.shape[0]):
    for j in range(len(grid_np_arr[i]) - 3):
        RESULT_ARRAY.append(grid_np_arr[i, j:j+4].prod())

In [ ]:
# Adjacent rows (UP/RIGHT)

In [18]:
grid_np_arr[:,0]

array([ 8, 49, 81, 52, 22, 24, 32, 67, 24, 21, 78, 16, 86, 19,  4, 88,  4,
       20, 20,  1])

In [10]:
# Step 2: Create a four adjacent numbers function from
adjacent_num = 4
grid_size = len(grid_np_arr)

In [11]:
# the max down (up/down)
up_down_lst = [grid_np_arr[k][j] for j in range(grid_size) for k in range(grid_size)]
up_down_lst

[8,
 49,
 81,
 52,
 22,
 24,
 32,
 67,
 24,
 21,
 78,
 16,
 86,
 19,
 4,
 88,
 4,
 20,
 20,
 1,
 2,
 49,
 49,
 70,
 31,
 47,
 98,
 26,
 55,
 36,
 17,
 39,
 56,
 80,
 52,
 36,
 42,
 69,
 73,
 70,
 22,
 99,
 31,
 95,
 16,
 32,
 81,
 20,
 58,
 23,
 53,
 5,
 0,
 81,
 8,
 68,
 16,
 36,
 35,
 54,
 97,
 40,
 73,
 23,
 71,
 60,
 28,
 68,
 5,
 9,
 28,
 42,
 48,
 68,
 83,
 87,
 73,
 41,
 29,
 71,
 38,
 17,
 55,
 4,
 51,
 99,
 64,
 2,
 66,
 75,
 22,
 96,
 35,
 5,
 97,
 57,
 38,
 72,
 78,
 83,
 15,
 81,
 79,
 60,
 67,
 3,
 23,
 62,
 73,
 0,
 75,
 35,
 71,
 94,
 35,
 62,
 25,
 30,
 31,
 51,
 0,
 18,
 14,
 11,
 63,
 45,
 67,
 12,
 99,
 76,
 31,
 31,
 89,
 47,
 99,
 20,
 39,
 23,
 90,
 54,
 40,
 57,
 29,
 42,
 89,
 2,
 10,
 20,
 26,
 44,
 67,
 47,
 7,
 69,
 16,
 72,
 11,
 88,
 1,
 69,
 0,
 60,
 93,
 69,
 41,
 44,
 26,
 95,
 97,
 20,
 15,
 55,
 5,
 28,
 7,
 3,
 24,
 34,
 74,
 16,
 75,
 87,
 71,
 24,
 92,
 75,
 38,
 63,
 17,
 45,
 94,
 58,
 44,
 73,
 97,
 46,
 94,
 62,
 31,
 92,
 4,
 17,
 40,
 68,
 36,

In [13]:
np_up_down = np.array(up_down_lst).reshape((int(len(up_down_lst)/adjacent_num),adjacent_num))
print(np_up_down)



[[ 8 49 81 52]
 [22 24 32 67]
 [24 21 78 16]
 [86 19  4 88]
 [ 4 20 20  1]
 [ 2 49 49 70]
 [31 47 98 26]
 [55 36 17 39]
 [56 80 52 36]
 [42 69 73 70]
 [22 99 31 95]
 [16 32 81 20]
 [58 23 53  5]
 [ 0 81  8 68]
 [16 36 35 54]
 [97 40 73 23]
 [71 60 28 68]
 [ 5  9 28 42]
 [48 68 83 87]
 [73 41 29 71]
 [38 17 55  4]
 [51 99 64  2]
 [66 75 22 96]
 [35  5 97 57]
 [38 72 78 83]
 [15 81 79 60]
 [67  3 23 62]
 [73  0 75 35]
 [71 94 35 62]
 [25 30 31 51]
 [ 0 18 14 11]
 [63 45 67 12]
 [99 76 31 31]
 [89 47 99 20]
 [39 23 90 54]
 [40 57 29 42]
 [89  2 10 20]
 [26 44 67 47]
 [ 7 69 16 72]
 [11 88  1 69]
 [ 0 60 93 69]
 [41 44 26 95]
 [97 20 15 55]
 [ 5 28  7  3]
 [24 34 74 16]
 [75 87 71 24]
 [92 75 38 63]
 [17 45 94 58]
 [44 73 97 46]
 [94 62 31 92]
 [ 4 17 40 68]
 [36 33 40 94]
 [78 35  3 88]
 [44 92 57 33]
 [72 99 49 33]
 [ 5 40 67 56]
 [54 53 67 39]
 [78 14 80 24]
 [37 13 32 67]
 [18 69 71 48]
 [ 7 98 53  1]
 [22 78 59 63]
 [96  0  4  0]
 [44 86 16 46]
 [ 8 82 48 61]
 [78 43 88 32]
 [40 36 54

In [ ]:
up_down = [sum(x) for x in np_up_down]

max_up_down = max(up_down)
max_up_down

In [6]:
left_right = []

np_left_right = [np.array(lr).reshape((int(len(grid_np_arr)/adjacent_num),adjacent_num)) for lr in grid_np_arr]

sum_left_right = []

for lr in np_left_right:
    sum_left_right = []
    for i in lr:
        sum_left_right.append(sum(i))
    left_right.append(sum(sum_left_right))
    
max_left_right = max(left_right)
max_left_right

1215

In [7]:
# diagonal
diagonal_lst = []
sum_diagonal = []

for m in range(grid_size):
#     print('m',np.diag(grid_np_arr,k=m))
#     print('mm',np.prod(np.diag(grid_np_arr,k=m)))
    diagonal_lst.append(np.prod(np.diag(grid_np_arr,k=m)))
    if m > 0:
        diagonal_lst.append(np.prod(np.diag(grid_np_arr,k=-m)))

max_diagonal =  max(diagonal_lst)        
max_diagonal

2083952640

## Part 2

For this part we will use the dataset `covid_19_data.csv` located in the `../datasets` folder.



In [8]:
df = pd.read_csv('../datasets/covid_19_data.csv')
df.head()

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

**1. What is the shape of this dataframe?**

**2. How many missing values are there? How do we find this out? Which column is problematic?**

In [9]:
# enter your code here


**3. In your own words, what could we do about the missing values? Should we remove rows with the missing values? Are they useful?**

**4. Where was the first observation of more than 100+ covid cases?**

**5. What was the date of the first confirmed covid case in the United States?**

**6. What caused the most amount of confirmed cases in U.S. during this period?**

**7. How many deaths occurred in the top 5 deadliest countries in the period of our data set?**

**8. Which country had the highest number of confirmed cases but zero deaths during this period?**

**9. Which country had the highest percent of deaths compared to its cases during this period?**

**10. What was the total number of confirmed cases by day?**

**11. Can you plot a chart from this dataset?**