# NumPy 

The fundamental package for scientific computing with Python

- [learn more](https://numpy.org/)
- [docs](https://numpy.org/doc/stable/)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
my_list = [-17,0,4,5,9]
my_list

[-17, 0, 4, 5, 9]

In [4]:
# numpy array from a list
my_np_arr = np.array(my_list)
my_np_arr

array([-17,   0,   4,   5,   9])

In [5]:
# perform parenthetic operations
# these operations are performed element by element
# multiply every element in the arrary by ten (10)
my_np_arr * 10

array([-170,    0,   40,   50,   90])

In [6]:
# create a numpy array from a tuple
my_tuple = (14,-3.54,5+7j)

Each of the element in the tuple was promoted to the final type within the array

The interger **14** was promoted to a complex number, which has **14 as a floating point number as its real part, and has zero as its imaginary or complex part**.

In [7]:
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

Within NumPy every element within an array has to have the **same type**

An interger can't accommodate a complex number or a floating point number a floating point number can't accommodate a complex number. **Complex numbers are needed for every element within the array** 

### Creating a header

Difference between Python and NumPy data structures.

In [8]:
my_tuple * 6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [9]:
np.array(my_tuple) * 6

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])

### Intrinsic NumPy array creation using NumPy's nethods

In [10]:
my_range = list(range(7))
my_range

[0, 1, 2, 3, 4, 5, 6]

In [11]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

Create an array using a function call with start and stop parameters

In [12]:
# use 10 as the start and 23 as the stop
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [13]:
np.arange(10,23,5) #every 5th integer as a step parameter

array([10, 15, 20])

In [14]:
# find the length of the array
np.arange(10,23).size
# 13 elements in the array

13

In [15]:
my_arr_size = np.arange(10,23,5)
my_arr_size.size
# 3 elements in the array

3

### linspace(), zeros(), ones(), and NumPy data types

The **linspace()** function creates a group of intergers that are evenly or lineraly spaced.
```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```
- [linspance function docs](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace)


In [16]:
np.linspace(5,15,9) # start, stop, num=50

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [17]:
# If True, return (samples, step), where step is the spacing between samples.
my_linspace = np.linspace(5,15,9,retstep=True)
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [18]:
my_linspace[1] # index of the step value in the array

1.25

The **zeros()** create an array where every element is set to zero.
```
numpy.zeros(shape, dtype=float, order='C')
```
- [zero function docs](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros)

In [19]:
# five component of the array equal to zero with floating point values
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
# 5 rows and 4 columns with each element equal to zero as a floating point values
two_dimensional_zeros = np.zeros((5,4)) 
two_dimensional_zeros 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# two_dimensional_zeros array with the first component 5 two dimensional array with 3 sqare brackets at the end
# the second component have 4 group of matrices 
# the last paramenter 3 tells us that each one of these arrays contains three columns.
three_dimensional_zeros = np.zeros((5,4,3)) 

The **ones()** creates an array where every element is set to one
```
numpy.ones(shape, dtype=None, order='C')
```
- [ones function docs](https://numpy.org/doc/stable/reference/generated/numpy.ones.html?highlight=ones#numpy.ones)

In [22]:
# five component f the array equal to one with floating point values
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
# 5 rows and 4 columns with each element equal to one as a floating point values
two_dimensional_ones = np.ones((5,4))
two_dimensional_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
three_dimensional_ones = np.ones((5,4,3)) 
three_dimensional_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### NumPy data types

Data types
[Array types and conversions between types](https://numpy.org/doc/stable/user/basics.types.html?highlight=data%20types#array-types-and-conversions-between-types)

**numpy.dtype.type**
```
dtype.type
```
The type object used to instantiate a scalar of this data-type.

In [25]:
np.zeros(11) # floating point values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
# create an array with zeros that has 11 elements
np.zeros(11,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

**numpy.ndarray**
```
class numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
```

An array object represents a multidimensional, homogeneous array of fixed-size items. An associated data-type object describes the format of each element in the array (its byte-order, how many bytes it occupies in memory, whether it is an integer, a floating point number, or something else, etc.)

**Parameters** (for the __new__ method; see Notes below)
- shape tuple of ints
Shape of created array.

- dtype data-type, optional
Any object that can be interpreted as a numpy data type.

- buffer object exposing buffer interface, optional
Used to fill the array with data.

- offset int, optional
Offset of array data in buffer.

- strides tuple of ints, optional
Strides of data in memory.

- order{‘C’, ‘F’}, optional
Row-major (C-style) or column-major (Fortran-style) order.



In [27]:
np.ndarray(shape=(2,2), dtype=float, order='F')

array([[1.26880891e-311, 1.06540832e-312],
       [2.16847421e-028, 0.00000000e+000]])

In [28]:
np.ndarray(shape=(2,2), dtype=int, order='C')

array([[         0, 1075314688],
       [         0,          0]])

In [29]:
np.ndarray((2,), buffer=np.array([1,2,3]),
           offset=np.int_().itemsize,
           dtype=int) # offset = 1*itemsize, i.e. skip first element

array([2, 3])

In [30]:
my_vector = np.array(my_list)
my_vector

array([-17,   0,   4,   5,   9])

In [31]:
my_vector[0]

-17

In [32]:
my_vector[0] = -102

In [33]:
my_vector

array([-102,    0,    4,    5,    9])

In [34]:
my_vector[-3]

4

In [35]:
my_vector[::-1] # reverse order

array([   9,    5,    4,    0, -102])

In [36]:
my_vector[-1] # last index element

9

In [37]:
my_vector[-3 % 2 ]

0

In [38]:
my_vector[305 % 5]

-102

In [39]:
print(my_vector.size)
my_vector[305 % my_vector.size]

5


-102

### Two dimensional Arrays

In [40]:
my_array = np.arange(35)
my_array.shape = (7,5) # 7 rows and 5 colunms
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [41]:
# access the third row in the array
my_array[3]

array([15, 16, 17, 18, 19])

In [42]:
# access the second to last row in the array
my_array[-2]

array([25, 26, 27, 28, 29])

In [43]:
# access the third row in the array and second element
print('my_array[3][2]:',my_array[3][2])

# my_array[row, column]
print('my_array[row, column]:', my_array[3,2])


my_array[3][2]: 17
my_array[row, column]: 17


In [44]:
# more abstractly and a technqie much more often used in data science work
row = 5
column = 2

my_array[row, column]


27

### Three dimensional Arrays

In [45]:
my_3D_array = np.arange(70) # 70 elements
my_3D_array.shape = (2,7,5) # an array that is 2 by 7 by 5

# 2 by 7 is 14 times 5 is equal to 70
print('a range element:',(2*7)*5)

my_3D_array # 7 rows and 5 columns

a range element: 70


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [46]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [47]:
my_3D_array[1,3] # first dimension and third index (0,1,2,3)

array([50, 51, 52, 53, 54])

In [48]:
my_3D_array[1,3,2] # first dimension, third index (0,1,2,3) and the colunm with second index

52

In [49]:
# assignment statement
my_3D_array[1,3,2] = 1111
my_3D_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

### Boolean Mask Arrays

In [50]:
my_vector = np.array(my_list)
my_vector

array([-17,   0,   4,   5,   9])

In [51]:
zero_mod_7_mask = 0 == (my_vector % 7)
zero_mod_7_mask

array([False,  True, False, False, False])

In [52]:
# This is the essential elements of Boolean Mask Arrays
sub_arr = my_vector[zero_mod_7_mask]
sub_arr

array([0])

In [53]:
sub_arr[sub_arr > 0]

array([], dtype=int32)

In [54]:
sub_arr[sub_arr > -1]

array([0])

### NumPy logical operators

In [55]:
mod_test = 0 == (my_vector % 7)
mod_test

array([False,  True, False, False, False])

In [56]:
positive_test = my_vector > 0
positive_test

array([False, False,  True,  True,  True])

In [57]:
positive_test[positive_test > 0]

array([ True,  True,  True])

In [58]:
my_vector[positive_test]

array([4, 5, 9])

#### numpy.logical_and
```
numpy.logical_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'logical_and'>
```
Compute the truth value of x1 AND x2 element-wise.

Parameters
- x1, x2 array_like
    - Input arrays. If x1.shape != x2.shape, they must be broadcastable to a common shape (which becomes the shape of the output).

In [59]:
np.logical_and(True, False)

False

In [60]:
np.logical_and([True, False], [False, False])

array([False, False])

In [61]:
x = np.arange(5)
print('x>1:',x>1)
print('x<4:',x<4)

np.logical_and(x>1, x<4)

x>1: [False False  True  True  True]
x<4: [ True  True  True  True False]


array([False, False,  True,  True, False])

In [62]:
print('mod_test',mod_test)
print('positive_test',positive_test)

combined_mask = np.logical_and(mod_test, positive_test)
combined_mask

mod_test [False  True False False False]
positive_test [False False  True  True  True]


array([False, False, False, False, False])

In [63]:
my_vector[combined_mask]

array([], dtype=int32)

### Broadcasting

The term **broadcasting** describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is __"broadcast"__ across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.
```
numpy.broadcast
```
- class **numpy.broadcast**
Produce an object that mimics broadcasting.



In [64]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [65]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)

In [66]:
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [67]:
my_3D_array = np.arange(70) # 70 elements from 0 to 69
my_3D_array.shape = (2,7,5) # an array that is 2 by 7 by 5

my_3D_array # 7 rows and 5 columns

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [68]:
# shape
my_3D_array.shape

(2, 7, 5)

#### numpy.broadcast.ndim
attribute
```
broadcast.ndim
```
Number of dimensions of broadcasted result. Alias for nd.

In [69]:
x = np.array([1, 2, 3])
y = np.array([[4], [5], [6]])
b = np.broadcast(x, y)
b.ndim

2

In [70]:
# number of dimensions
# The ndim confirms the array has three dimensions
my_3D_array.ndim

3

In [71]:
# size: the number of elements in the array
my_3D_array.size

70

In [72]:
# datatype for each element
my_3D_array.dtype

dtype('int32')

#### Explain how to use broadcast

Begin to explain how we can use broadcasting

In [73]:
# scalers
# 5 times three-dimensional array
5 * my_3D_array - 2 
# (5 * 0) - 2 = -2
# (5 * 1) - 2 = 3
# (5 * 2) - 2 = 8

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

#### numpy.inner
```
numpy.inner(a, b)
```
Inner product of two arrays.

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.



In [74]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [75]:
# create two numpy arrays
left_mat = np.arange(6).reshape(2,3)
print('left_mat\n',left_mat)

right_mat = np.arange(15).reshape(3,5)
print('right_mat\n',right_mat)


left_mat
 [[0 1 2]
 [3 4 5]]
right_mat
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [76]:
a = np.arange(24).reshape((2,3,4))
print('a',a)

b = np.arange(4)
print('b',b)

np.inner(a, b)

a [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b [0 1 2 3]


array([[ 14,  38,  62],
       [ 86, 110, 134]])

#### numpy.dot
```
numpy.dot(a, b, out=None)
```
Dot product of two arrays. Specifically,

In [77]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [78]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
print('a\n',a)

b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print('b\n',b)

np.dot(a, b)[2,3,2,1,2,2]

a
 [[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 20

499128

In [79]:
sum(a[2,3,2,:] * b[1,2,:,2])

499128

In [80]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

#### Operations along axes

In [81]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [82]:
my_3D_array.shape

(2, 7, 5)

In [83]:
my_3D_array.sum()

2415

In [84]:
(60 * 30) / 2

900.0

#### numpy.sum
```
numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
```
Sum of array elements over a given axis.

In [85]:
np.sum([0.5, 1.5])

2.0

In [86]:
np.sum([0.5, 0.7, 0.2, 1.5])

2.9

In [87]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype='int32')

1

In [88]:
np.sum([[0, 1], [0, 5]])

6

In [89]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [90]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [91]:
np.sum([[0, 1], [np.nan, 5]], where=[False, True], axis=1)

array([1., 5.])

In [92]:
np.ones(128, dtype='int8').sum(dtype='int8')

-128

In [93]:
my_3D_array.sum(axis=0)
# [ 0, ] + [[35,] = [35]
# [ 0,  1,] + [35, 36]= [35.37]

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [94]:
# [ 0,  1,  2,  3,  4],
# [ 5,  6,  7,  8,  9],
# [10, 11, 12, 13, 14],
# [15, 16, 17, 18, 19],
# [20, 21, 22, 23, 24],
# [25, 26, 27, 28, 29],
# [30, 31, 32, 33, 34]]

first_col = sum([0,5,10,15,20,25,30])
print('first_col',first_col)

second_col = sum([1,6,11,16,21,26,31])
print('second_col',second_col)

my_3D_array.sum(axis=1)

first_col 105
second_col 112


array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [95]:
# [ 0,  1,  2,  3,  4],
# [ 5,  6,  7,  8,  9],
first_row = sum([ 0,  1,  2,  3,  4])
print('first_row',first_row)

second_row = sum([ 5,  6,  7,  8,  9])
print('second_row',second_row)

my_3D_array.sum(axis=2)

first_row 10
second_row 35


array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

Broadcasting with two or more arrays
- the smaller array is broadcasting across the larger array

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when

- they are equal, or
- one of them is 1

[learn more](https://numpy.org/doc/stable/user/basics.broadcasting.html?highlight=broadcasting#general-broadcasting-rules)

In [96]:
x = np.arange(4)
xx = x.reshape(4,1)
print(x)
print(xx)
x.shape

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


(4,)

In [97]:
y = np.ones(5)
z = np.ones((3,4))
print(y)
print(z)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [98]:
y.shape

(5,)

**x + y**
```
ValueError                                Traceback (most recent call last)
<ipython-input-105-cd60f97aa77f> in <module>
----> 1 x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 
```

In [99]:
xx.shape

(4, 1)

In [100]:
(xx + y).shape

(4, 5)

In [101]:
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [102]:
(x + z).shape

(3, 4)

In [103]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

In [104]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [105]:
# Create an array with 35 elements and dtype of interger. reshape it to have 7 rows and 5 columns
print('standard\n',np.ones(35, dtype='int_'))
print('reshape\n',np.ones(35, dtype='int_').reshape(7,5) )
my_3D_array = np.ones(35, dtype='int_').reshape(7,5) * 3
my_3D_array

standard
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
reshape
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [106]:
my_random_3D_array = np.random.random((7,5))
my_random_3D_array

array([[0.34533809, 0.12061891, 0.47161839, 0.21373629, 0.17065194],
       [0.16408221, 0.07797727, 0.80457266, 0.12494342, 0.41895805],
       [0.58913565, 0.19181859, 0.66451813, 0.89126761, 0.01882802],
       [0.14779999, 0.92124186, 0.89951511, 0.84326379, 0.76692961],
       [0.6415265 , 0.92436507, 0.9579605 , 0.04094168, 0.32365991],
       [0.18792758, 0.94502533, 0.81879752, 0.50498534, 0.99250177],
       [0.26574035, 0.32808418, 0.29526443, 0.80307526, 0.38200012]])

In [107]:
np.set_printoptions(precision=4)

In [108]:
# [3, 3, 3, 3, 3]
# [0.2012, 0.2004, 0.0108, 0.9131, 0.1128]
# [(3*0.2012) = 0.6036, 0.6011, 0.0325, 2.7392, 0.3385]
my_3D_array * my_random_3D_array

array([[1.036 , 0.3619, 1.4149, 0.6412, 0.512 ],
       [0.4922, 0.2339, 2.4137, 0.3748, 1.2569],
       [1.7674, 0.5755, 1.9936, 2.6738, 0.0565],
       [0.4434, 2.7637, 2.6985, 2.5298, 2.3008],
       [1.9246, 2.7731, 2.8739, 0.1228, 0.971 ],
       [0.5638, 2.8351, 2.4564, 1.515 , 2.9775],
       [0.7972, 0.9843, 0.8858, 2.4092, 1.146 ]])

In [109]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [110]:
my_3D_array / my_vector

array([[-3.    ,  0.4286,  0.2143,  0.1429,  0.1071],
       [-3.    ,  0.4286,  0.2143,  0.1429,  0.1071],
       [-3.    ,  0.4286,  0.2143,  0.1429,  0.1071],
       [-3.    ,  0.4286,  0.2143,  0.1429,  0.1071],
       [-3.    ,  0.4286,  0.2143,  0.1429,  0.1071],
       [-3.    ,  0.4286,  0.2143,  0.1429,  0.1071],
       [-3.    ,  0.4286,  0.2143,  0.1429,  0.1071]])

In [111]:
my_3D_array % my_vector

array([[0, 3, 3, 3, 3],
       [0, 3, 3, 3, 3],
       [0, 3, 3, 3, 3],
       [0, 3, 3, 3, 3],
       [0, 3, 3, 3, 3],
       [0, 3, 3, 3, 3],
       [0, 3, 3, 3, 3]], dtype=int32)

### Creating Structured Arrays

data definition for a structured array

```
dt = np.dtype('i4')   # 32-bit signed integer
dt = np.dtype('f8')   # 64-bit floating-point number
dt = np.dtype('c16')  # 128-bit complex floating-point number
dt = np.dtype('a25')  # 25-length zero-terminated bytes
dt = np.dtype('U25')  # 25-character string
```

https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [112]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype


array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [113]:
# The data definition describes an array that has four fields
# The first is a string, which is named name, float point, float point, interger
person_data_def = [('name',np.dtype('U25')),('height',np.dtype('f8') ),('weight',np.dtype('f8') ),('age',np.dtype('i4'))]
person_data_def

[('name', dtype('<U25')),
 ('height', dtype('float64')),
 ('weight', dtype('float64')),
 ('age', dtype('int32'))]

In [114]:
people_array = np.zeros((4,), dtype=person_data_def)
people_array

array([('', 0., 0., 0), ('', 0., 0., 0), ('', 0., 0., 0), ('', 0., 0., 0)],
      dtype=[('name', '<U25'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i4')])

In [115]:
people_array[3] = ('delta', 73,205,34)

In [116]:
people_array[0] = ('alpha', 65, 112, 23)

In [117]:
people_array

array([('alpha', 65., 112., 23), ('',  0.,   0.,  0), ('',  0.,   0.,  0),
       ('delta', 73., 205., 34)],
      dtype=[('name', '<U25'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i4')])

In [118]:
people_array[0:]

array([('alpha', 65., 112., 23), ('',  0.,   0.,  0), ('',  0.,   0.,  0),
       ('delta', 73., 205., 34)],
      dtype=[('name', '<U25'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i4')])

In [119]:
# selection and assignment
ages = people_array['age']
ages

array([23,  0,  0, 34])

In [120]:
names = people_array['name']
names

array(['alpha', '', '', 'delta'], dtype='<U25')

In [121]:
make_youthful = ages / 2
make_youthful

array([11.5,  0. ,  0. , 17. ])

### Multi-dimensional Structured Arrays


In [122]:
# Createa new array that hass four by three by two elemens
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]],

       [[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]],

       [[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]],

       [[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]]],
      dtype=[('name', '<U25'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i4')])

In [123]:
people_big_array[3,2,1] = ('echo',68,115,46)

In [124]:
people_big_array

array([[[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)]],

       [[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)]],

       [[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)]],

       [[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('echo', 68., 115., 46)]]],
      dtype=[('name', '<U25'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i4')])

In [125]:
people_big_array['height']

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0., 68.]]])

In [126]:
people_big_array[['height', 'weight']]

array([[[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), (68., 115.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[100,108], 'itemsize':120})

### Creating Record Array

record arrays are structured arrays wrapped using a sub-class of ndarray called **numpy.record** array

#### numpy.record
```
class numpy.record
```
A data-type scalar that allows field access as attribute lookup.

List can contain heterogeneous values such as integers, floats, strings, tuples, lists, and dictionaries but they are commonly used to store collections of homogeneous objects. Python lists are mutable sequences.
Lists should always be used when we want to store items in some kind of order. The keys for a list are integers.

In [127]:
# Wrapping allows field access by attribute on an array object
person_record_array = np.rec.array([('delta', 73,205,34), ('alpha', 65, 112, 23)], dtype=person_data_def)
person_record_array

rec.array([('delta', 73., 205., 34), ('alpha', 65., 112., 23)],
          dtype=[('name', '<U25'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i4')])

In [128]:
person_record_array[0]

('delta', 73., 205., 34)

In [129]:
# instead of using an index, use an attribute
# structured and record arrays are designed for heterogeneous data while maintaining NumPy's requirement that every element in an array use the same amount of memory spaces
person_record_array[0].age

34

# NumPy: Access an array by column

Write a NumPy program to access an array by column.

https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-81.php

In [130]:
# import numpy as np
x= np.arange(9).reshape(3,3)
print("Original array elements:")
print(x)
print("Access an array by column:")
print("First column:")
print(x[:,0])
print("Second column:")
print(x[:,1])
print("Third column:")
print(x[:,2])


Original array elements:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Access an array by column:
First column:
[0 3 6]
Second column:
[1 4 7]
Third column:
[2 5 8]
