<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 style="padding: 2220px 210px -30px 0px;">Week 14 Lab</h1>
</div>

In [1]:
# imports

import numpy as np

## Exercise 1

Create the following numpy arrays:
    
a) An array using the following lists (make it interesting if you can)

In [2]:
l = [0,0,0,0,0] 
m = [1,2,3,4,5]

arr = np.array(l+m)
arr.shape = (2,5)
arr

array([[0, 0, 0, 0, 0],
       [1, 2, 3, 4, 5]])

b) A 3 x 4 matrix of zeros: 

In [3]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

c) A 2 x 4 matrix of zeros and ones of the following format:

[[0,0,1,1], [0,0,1,1]]

(try without using python lists)

In [4]:
a = np.zeros(2,dtype='int64')
b = np.ones(2,dtype='int64')
print(a,b)
ab_merge = np.concatenate((a, b), axis=0)
ab_merge

[0 0] [1 1]


array([0, 0, 1, 1], dtype=int64)

In [5]:
ab = np.array([0]*2 + [1]*2)
ab_mix = np.array([ab]*2)
ab_mix

array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

e) A 3 x 4 array from the following numpy array (do not change the already existing code):

In [6]:
r = np.arange(0,12)
# enter your code below
r.shape = (3,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

f) A 1 x 13 array from the following array

look into the `resize` method

In [7]:
n = np.empty(shape=(2,6))
### enter your code below
np.resize(n,(1,13))
n

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

) using the following array, create an array that consists of the same numbers but squared and in order from smallest to largest

In [8]:
n = np.array([7, 6, 9, 5, 8, 9, 6, 10, 3, 4, 3, 3, 1, 2, 5, 8, 6, 1, 6, 0])
# enter your code below
n_sort = np.sort(n) ** 2
n_sort

array([  0,   1,   1,   4,   9,   9,   9,  16,  25,  25,  36,  36,  36,
        36,  49,  64,  64,  81,  81, 100], dtype=int32)

## Exercise 2

Produce  the array as asked

a) Create a 3x3x3 array with the numbers from 1, 27. Then slice it to produce the 3x3 array in the middle.

In [9]:
j = np.arange(1,28)
print('j\n',j)

j_reshape = j.reshape(3,3,3)
print('j_reshape\n',j_reshape)

j_slice = j_reshape[:3:3]
print('j_slice\n',j_slice)


j
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
j_reshape
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
j_slice
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


b) Create a 3 x 3 array of random numbers. Then slice it to produce the numbers in the 2-index column.

In [10]:
rng = np.random.default_rng(0)
# enter your code below 

rng_standard_normal = [rng.standard_normal() for x in range(9)]
print(rng_standard_normal)

rng_arr = np.array(rng_standard_normal)

[0.1257302210933933, -0.1321048632913019, 0.6404226504432821, 0.10490011715303971, -0.535669373161111, 0.36159505490948474, 1.3040000451301372, 0.9470809631292422, -0.7037352358069926]


In [11]:
# Create a 3 x 3 array of random numbers. 
rng_arr.reshape(3,3)

array([[ 0.12573022, -0.13210486,  0.64042265],
       [ 0.10490012, -0.53566937,  0.36159505],
       [ 1.30400005,  0.94708096, -0.70373524]])

In [12]:
# Then slice it to produce the numbers in the 2-index column
rng_2nd_col = rng_arr.reshape(3,3)
rng_2nd_col[:,1]

array([-0.13210486, -0.53566937,  0.94708096])

c) Create a 3x3x3 array of zeros. Slice a 2x2 array from it and change the values to 1s. Then output the original 3x3x3 with `0`'s and `1`s

In [13]:
# Create a 3x3x3 array of zeros. 
np_zeros = np.zeros((3,3,3),dtype='int64')
np_zeros

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [14]:
# Slice a 2x2 array from it and change the values to 1s. 
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((2,2),dtype='int64') + 1

array([[1, 1],
       [1, 1]], dtype=int64)

d) Create an array of all the numbers from 1, 27 (inclusive). Then produce a slice that outputs only the even numbers less than 14.

In [16]:
# Create an array of all the numbers from 1, 27 (inclusive).
n_arr = np.array(np.arange(1,27))

# Then produce a slice that outputs only the even numbers less than 14.
n_slice = np.array(n_arr[:14])
positive_test = 0 == (n_slice % 2)
n_slice[positive_test]

array([ 2,  4,  6,  8, 10, 12, 14])

## Exercise 3

a) Create an array of all postive integers from 1 to 100.    
b) Reshape it into a 10 x 10 matrix  
c) Remove multiples (so numbers that aren't prime  
d) Output the prime numbers.  

a)

In [17]:
pos_int = np.arange(1,101)
np.array(pos_int)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

b) reshape it into a 10 x 10 matrix

In [18]:
pos_int.reshape((10, 10))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

c) starting with 2 (until you get to sqrt(100) or 10), replace multiples of that number with 0

In [19]:
# n_sqrt = np.array(np.arange(100))
n_sqrt = np.arange(100)
print(n_sqrt)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


d) Using a slice, output your prime sieve containing all of the prime numbers less than 0 (be sure to exclude 1 from your slice)

hint: the length of such slice should be `25`