<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 style="padding: 2220px 210px -30px 0px;">Week 14 Lab</h1>
</div>

In [1]:
# imports

import numpy as np

## Exercise 1

Create the following numpy arrays:
    
a) An array using the following lists (make it interesting if you can)

In [21]:
l = [0,0,0,0,0] 
m = [1,2,3,4,5]

arr = np.array(l+m)
arr.shape = (2,5)
arr

array([[0, 0, 0, 0, 0],
       [1, 2, 3, 4, 5]])

b) A 3 x 4 matrix of zeros: 

In [15]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

c) A 2 x 4 matrix of zeros and ones of the following format:

[[0,0,1,1], [0,0,1,1]]

(try without using python lists)

In [61]:
a = np.zeros(2,dtype='int64')
b = np.ones(2,dtype='int64')
print(a,b)
ab_merge = np.concatenate((a, b), axis=0)
ab_merge

[0 0] [1 1]


array([0, 0, 1, 1], dtype=int64)

In [62]:
ab = np.array([0]*2 + [1]*2)
ab_mix = np.array([ab]*2)
ab_mix

array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

e) A 3 x 4 array from the following numpy array (do not change the already existing code):

In [65]:
r = np.arange(0,12)
# enter your code below
r.shape = (3,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

f) A 1 x 13 array from the following array

look into the `resize` method

In [67]:
n = np.empty(shape=(2,6))
### enter your code below
np.resize(n,(1,13))
n

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

) using the following array, create an array that consists of the same numbers but squared and in order from smallest to largest

## Exercise 2

Produce  the array as asked

a) Create a 3x3x3 array with the numbers from 1, 27. Then slice it to produce the 3x3 array in the middle.

In [120]:
j = np.arange(1,28)
print('j\n',j)

j_reshape = j.reshape(3,3,3)
print('j_reshape\n',j_reshape)

j_slice = j_reshape[:3:3]
print('j_slice\n',j_slice)


j
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
j_reshape
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
j_slice
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


b) Create a 3 x 3 array of random numbers. Then slice it to produce the numbers in the 2-index column.

In [123]:
rng = np.random.default_rng(0)
### enter your code below 
print('rng',rng)

rng Generator(PCG64)


c) Create a 3x3x3 array of zeros. Slice a 2x2 array from it and change the values to 1s. Then output the original 3x3x3 with `0`'s and `1`s

d) Create an array of all the numbers from 1, 27 (inclusive). Then produce a slice that outputs only the even numbers less than 14.

## Exercise 3

a) Create an array of all postive integers from 1 to 100.    
b) Reshape it into a 10 x 10 matrix  
c) Remove multiples (so numbers that aren't prime  
d) Output the prime numbers.  

a)

b) reshape it into a 10 x 10 matrix

c) starting with 2 (until you get to sqrt(100) or 10), replace multiples of that number with 0

d) Using a slice, output your prime sieve containing all of the prime numbers less than 0 (be sure to exclude 1 from your slice)

hint: the length of such slice should be `25`